---
title: "Project"
author: "Parth Gupta"
date: "12/4/2021"
output: html_document
---

```{r}
# Load packages
library("plotly")
library("tidyverse")
#library("tidentityentityyverse")
library("data.table")
#library("gridentityentityExtra")
library("knitr")
library(grid)
library(gridExtra)

# Load athletes_events data 
data <- read_csv("athlete_events.csv",
                 col_types = cols(
                   identity = col_character(),
                   Name = col_character(),
                   Sex = col_factor(levels = c("M","F")),
                   Age =  col_integer(),
                   Height = col_double(),
                   Weight = col_double(),
                   Team = col_character(),
                   NOC = col_character(),
                   Games = col_character(),
                   Year = col_integer(),
                   Season = col_factor(levels = c("Summer","Winter")),
                   City = col_character(),
                   Sport = col_character(),
                   Event = col_character(),
                   Medal = col_factor(levels = c("Gold","Silver","Bronze"))
                 )
)

# Options
opts_chunk$set(warning=FALSE, message=FALSE)
```
```{r}

# count number of athletes, nations, & events, excluding the Art Competitions
counts <- data %>% filter(Sport != "Art Competitions") %>%
  group_by(Year, Season) %>%
  summarize(
    Athletes = length(unique(identity)),
    Nations = length(unique(NOC)),
    Events = length(unique(Event))
  )

# plot
p1 <- ggplot(counts, aes(x=Year, y=Athletes, group=Season, color=Season)) +
  geom_point(size=2) +
  geom_line() +
  scale_color_manual(values=c("darkorange","darkblue")) +
  xlab("") +  
  annotate("text", x=c(1932,1956,1976,1980),
           y=c(2000,2750,6800,4700),
           label=c("L.A. 1932","Melbourne 1956","Montreal 1976","Moscow 1980"),
           size=3) +
  annotate("text",x=c(1916,1942),y=c(10000,10000),
           label=c("WWI","WWII"), size=4, color="red") +
  geom_segment(mapping=aes(x=1914,y=8000,xend=1918,yend=8000),color="red", size=2) +
  geom_segment(mapping=aes(x=1939,y=8000,xend=1945,yend=8000),color="red", size=2)
p2 <- ggplot(counts, aes(x=Year, y=Nations, group=Season, color=Season)) +
  geom_point(size=2) +
  geom_line() +
  scale_color_manual(values=c("darkorange","darkblue")) +
  xlab("") +  
  annotate("text", x=c(1932,1976,1980),
           y=c(60,105,70),
           label=c("L.A. 1932","Montreal 1976","Moscow 1980"),
           size=3)
p3 <- ggplot(counts, aes(x=Year, y=Events, group=Season, color=Season)) +
  geom_point(size=2) +
  geom_line() +
  scale_color_manual(values=c("darkorange","darkblue"))

p1
p2
p3
```
```{r}
# Subset to Art Competitions and variables of interest
art <- data %>% 
  filter(Sport == "Art Competitions") %>%
  select(Name, Sex, Age, Team, NOC, Year, City, Event, Medal)

# Count Events, Nations, and Artists each year
counts_art <- art %>% filter(Team != "Unknown") %>%
  group_by(Year) %>%
  summarize(
    Events = length(unique(Event)),
    Nations = length(unique(Team)),
    Artists = length(unique(Name))
  )

# Create plots
p4 <- ggplot(counts_art, aes(x=Year, y=Events)) +
  geom_point(size=2) +
  geom_line() + xlab("")
p5 <- ggplot(counts_art, aes(x=Year, y=Nations)) +
  geom_point(size=2) +
  geom_line() + xlab("")
p6 <- ggplot(counts_art, aes(x=Year, y=Artists)) +
  geom_point(size=2) +
  geom_line()
grid.arrange(p4, p5, p6, ncol=1)
```
```{r}
# count number of medals awarded to each Team
medal_counts_art <- art %>% filter(!is.na(Medal))%>%
  group_by(Team, Medal) %>%
  summarize(Count=length(Medal)) 

# order Team by total medal count
levs_art <- medal_counts_art %>%
  group_by(Team) %>%
  summarize(Total=sum(Count)) %>%
  arrange(Total) %>%
  select(Team)
medal_counts_art$Team <- factor(medal_counts_art$Team, levels=levs_art$Team)

# plot
ggplot(medal_counts_art, aes(x=Team, y=Count, fill=Medal)) +
  geom_col() +
  coord_flip() +
  scale_fill_manual(values=c("gold1","gray70","gold4")) +
  ggtitle("Historical medal counts from Art Competitions") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
# count number of medals awarded to each Team at Nazi Olympics
medal_counts_art_nazis <- art %>% filter(Year==1936, !is.na(Medal))%>%
  group_by(Team, Medal) %>%
  summarize(Count=length(Medal)) 

# order Team by total medal count
levs_art_nazis <- medal_counts_art_nazis %>%
  group_by(Team) %>%
  summarize(Total=sum(Count)) %>%
  arrange(Total) %>%
  select(Team)
medal_counts_art_nazis$Team <- factor(medal_counts_art_nazis$Team, levels=levs_art_nazis$Team)

# plot
ggplot(medal_counts_art_nazis, aes(x=Team, y=Count, fill=Medal)) +
  geom_col() +
  coord_flip() +
  scale_fill_manual(values=c("gold1","gray70","gold4")) +
  ggtitle("Nazi domination of Art Competitions at the 1936 Olympics") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
# Exclude art competitions from data (I won't use them again in the kernel)
data <- data %>% filter(Sport != "Art Competitions")

# Recode year of Winter Games after 1992 to match the next Summer Games
# Thus, "Year" now applies to the Olympiad in which each Olympics occurred 
original <- c(1994,1998,2002,2006,2010,2014)
new <- c(1996,2000,2004,2008,2012,2016)
for (i in 1:length(original)) {
  data$Year <- gsub(original[i], new[i], data$Year)
}
data$Year <- as.integer(data$Year)

# Table counting number of athletes by Year and Sex
counts_sex <- data %>% group_by(Year, Sex) %>%
  summarize(Athletes = length(unique(identity)))
counts_sex$Year <- as.integer(counts_sex$Year)

# Plot number of male/female athletes vs time
ggplot(counts_sex, aes(x=Year, y=Athletes, group=Sex, color=Sex)) +
  geom_point(size=2) +
  geom_line()  +
  scale_color_manual(values=c("darkblue","red")) +
  labs(title = "Number of male and female Olympians over time") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r, fig.width=11, fig.height=4}

men_age <- filter(data, Sex == "M")
women_age <- filter(data, Sex == "F")

ggplot(men_age, aes(y = Age, x = as.factor(Year))) +
  geom_boxplot() + 
  labs(title = "Distribution of Male participants from 1896 to 2016",
       x = "Year",
       y = "Age")

ggplot(women_age, aes(y = Age, x = as.factor(Year))) +
  geom_boxplot() + 
  labs(title = "Distribution of Female participants from 1896 to 2016",
       x = "Year",
       y = "Age")

```
```{r}
age_m <- data%>%filter(!is.na(Age), Season=='Summer')
age_m$Medal <- ifelse(is.na(age_m$Medal),"No medal",ifelse(age_m$Medal=="Gold","Gold",ifelse(age_m$Medal=="Silver","Silver","Bronze")))

order <- c('Gold', 'Silver', 'Bronze', 'No medal')

age_m$Medal <- fct_relevel(age_m$Medal, order)

bp <-ggplot(age_m, aes(y = Age, x = Medal, fill= Medal)) +
  geom_boxplot()+ 
  labs(title = "Distribution of Age of olympians",
       x = "Medal type",
       y = "Age") + facet_grid(cols = vars(Sex))
bp + scale_fill_manual(breaks = c("Gold", "Silver", "Bronze", 'No medal'), 
                       values=c("#C9B037", "#D7D7D7", "#6A3805", 'black'))
```
```{r}
age_m <- data%>%filter(!is.na(Age), Season=='Winter')
age_m$Medal <- ifelse(is.na(age_m$Medal),"No medal",ifelse(age_m$Medal=="Gold","Gold",ifelse(age_m$Medal=="Silver","Silver","Bronze")))

order <- c('Gold', 'Silver', 'Bronze', 'No medal')

age_m$Medal <- fct_relevel(age_m$Medal, order)

bp <-ggplot(age_m, aes(y = Age, x = Medal, fill= Medal)) +
  geom_boxplot()+ 
  labs(title = "Distribution of Age of olympians",
       x = "Medal type",
       y = "Age") + facet_grid(cols = vars(Sex))
bp + scale_fill_manual(breaks = c("Gold", "Silver", "Bronze", 'No medal'), 
                       values=c("#C9B037", "#D7D7D7", "#6A3805", 'black'))
```